### ISSUE TITLE
Hi Thenikso, do you have a visible demo?

### ISSUE THREAD

**Issue by JennieJi** [thenikso/angular-flo#1]
Hi Thenikso, 

For some reason, I am also working on something like this to make the JS code of the project more manageable. And also my back-end partners expect the flow of angular apps can be visible exactly as we draw in the Visio or something like this. You probably know the design view in Visual Studio can do this kind of stuff for C# and C++. May be in the future you only need to drag and drop elements with few JS code to create the entire app. Well, I have just abort my first version and trying to do in a better way.

I am so happy to see someone have create such a repository trying to fix this. But to tell the truth, I still think the way you did is not so easy to use. Do you have a live demo for this?

**Comment by thenikso** [comment]
Hi there! 
Before writing angular-flo I was working on a Quartz Composer like UI for javascript components but (I now checked) it wasn't jet using angular-flo. I can send it to you via mail if you wish.

All the code that uses angular-flo is in its specs and in `proof.html`.

If it can help, I believe that the project that got me inspired on flow based programming, much like you are now, is [NoFlo](http://noflojs.org) which already has a sparkly UI.

I'm also often brought back to the idea that visual programming should be a thing. Let me know where does it gets you and if you'd like to continue developing angular-flo!
